Document: sparky-office
Title: Debian sparky-office Manual
Author: <insert document author here>
Abstract: This manual describes what sparky-office is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparky-office/sparky-office.sgml.gz

Format: postscript
Files: /usr/share/doc/sparky-office/sparky-office.ps.gz

Format: text
Files: /usr/share/doc/sparky-office/sparky-office.text.gz

Format: HTML
Index: /usr/share/doc/sparky-office/html/index.html
Files: /usr/share/doc/sparky-office/html/*.html
